{{- if .Values.enableIstioGateway }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "customer.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
{{ end }}