{{- if .Values.enableIstioGateway }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "customer.fullname" . }}-{{ include "customer.version" . }}-vs
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "customer.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" (include "customer.fullname" .) .Release.Namespace }}
            subset: {{ include "customer.version" . }}
            port:
              number: {{ .Values.service.port }}
{{ end }}