{{- if not .Values.image.tag -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recommendation.fullname" . }}
  labels:
    {{- include "recommendation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "recommendation.selectorLabels" . | nindent 4 }}
{{- end }}